resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
<<<<<<< Updated upstream
- name: manager-config
  files:
  - controller_manager_config.yaml
=======
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: minchou/kruiserollout
  newTag: br-2
>>>>>>> Stashed changes
