# permissions for end users to edit batchreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: batchrelease-editor-role
rules:
- apiGroups:
  - rollouts.kruise.io
  resources:
  - batchreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollouts.kruise.io
  resources:
  - batchreleases/status
  verbs:
  - get
