# permissions for end users to view rollouthistories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rollouthistory-viewer-role
rules:
- apiGroups:
  - rollouts.kruise.io
  resources:
  - rollouthistories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollouts.kruise.io
  resources:
  - rollouthistories/status
  verbs:
  - get
