/*
Copyright 2022 The Kruise Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// RolloutHistorySpec defines the desired state of RolloutHistory
type RolloutHistorySpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// RolloutID should be changed before each workload revision publication.
	// It is to distinguish consecutive multiple workload publications and rollout progress.
	RolloutID string `json:"rolloutID,omitempty"`
	// ObjectRef indicates workload
	ObjectRef ObjectRef `json:"objectRef"`
	// Steps define the order of phases to execute release in batches(20%, 40%, 60%, 80%, 100%)
	// +optional
	Steps []CanaryStep `json:"steps,omitempty"`
	// TrafficRoutings hosts all the supported service meshes supported to enable more fine-grained traffic routing
	// todo current only support one TrafficRouting
	TrafficRoutings []*TrafficRouting `json:"trafficRoutings,omitempty"`
	// RealseType should be "batchRelease" or "rolloutRelease"
	ReleaseType string `json:"releasetype,omitepty"`
	// StepNum indicates how many steps this rollout is
	StepNum int64 `json:"stepnum,omitempty"`
}

// RolloutHistoryStatus defines the observed state of RolloutHistory
type RolloutHistoryStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// CurrentStep indicates the current step
	CurrentStep int64 `json:"currentstep,omitempty"`
	// RHPhase indicates state of this rollout revision, such as "init", "paused", "ready", "wait", "completed".
	RHPhase string `json:"rhphase,omitepty"`
	// Canary describes the state of the canary rollout
	// +optional
	CanaryStatus []CanaryStatus `json:"canaryStatus,omitempty"`
	// Conditions a list of conditions a rollout can have.
	// +optional
	Conditions []RolloutCondition `json:"conditions,omitempty"`
	// PodList include the info that generated by all the new pods in the rollout process
	PodList []PodInfoList `json:"podlist,omitempty"`
	// +optional
	//BlueGreenStatus *BlueGreenStatus `json:"blueGreenStatus,omitempty"`
	// Phase is the rollout phase.
	Phase RolloutPhase `json:"phase,omitempty"`
	// Message provides details on why the rollout is in its current phase
	Message string `json:"message,omitempty"`
}

// PodInfo indicates the pods for a revision
type PodInfoList struct {
	// Pods indicates the pods` information
	Pods []PodInfo `json:"pods,omitempty"`
}

// PodInfo indicates the information of pod
type PodInfo struct {
	// IP indicates the pod ip
	IP string `json:"ip,omitempty"`
	// Node indicates the node which pod is located at
	Node string `json:"node,omitempty"`
	// Name indicates the node name
	Name string `json:"name,omitempty"`
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// RolloutHistory is the Schema for the rollouthistories API
type RolloutHistory struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RolloutHistorySpec   `json:"spec,omitempty"`
	Status RolloutHistoryStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// RolloutHistoryList contains a list of RolloutHistory
type RolloutHistoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RolloutHistory `json:"items"`
}

func init() {
	SchemeBuilder.Register(&RolloutHistory{}, &RolloutHistoryList{})
}
